altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  8e243d96-12af-4a4e-a669-e4a476581f44:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-12T10:57:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f6448611-3f06-46c0-be6a-aa54941aae68
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 32f39894-b254-4a31-8cb8-6733e67a5f6e
        userCondition: null
fs: audio
handle: audio
name: Audio
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
