altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  19c22bfb-bad9-4cdb-9a0c-22dca3e75890:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-19T10:01:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 17c2c628-eb42-4484-803a-b0160c58d06f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03cab430-5099-4028-b187-c6c6e9d2bf69
        userCondition: null
fs: icons
handle: icons
name: Icons
sortOrder: 4
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: icons
transformSubpath: ''
