altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  18b9cd41-08c5-40fe-9739-2d51bffc6b7d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-12T10:57:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1c25a318-5f37-4dd2-a2d8-d2cb7a40cb01
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e15f0a12-a52b-4ee0-8f5d-3fbd0adc4974
        userCondition: null
fs: videos
handle: videos
name: Videos
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
