altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  9ce1b94a-a095-43c3-804e-7ab5507b65da:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-27T18:26:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 71c177ad-15d9-461d-bc09-18c8f9160e5a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 80181964-af3a-46b2-baa9-617cededf5d9
        userCondition: null
fs: audio
handle: audioVolume
name: 'Audio Volume'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
