altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  db12d40d-4b35-49d5-b34e-514e23ace4df:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-27T18:24:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ba35652b-1f5d-420a-8f88-a8419e2c7363
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8a1b27bb-07a3-42e0-9585-a8269a05d393
        userCondition: null
fs: general
handle: generalVolume
name: 'General Volume'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
