defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9afae938-5b2e-48b4-8129-4f720b7bf9dd # hero
  -
    uid: 01f9a30f-b79d-4ac9-9c06-c4e9ceb41b18 # Project
  -
    uid: 905a3727-eeb7-41a5-bb63-68e06a9fd97a # landingPage
handle: homePage
maxAuthors: 1
name: HomePage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0fad98d5-70b6-4371-8d2a-c5c8cd117e25: # Portfolio - Van Steenbergen Arno
    enabledByDefault: true
    hasUrls: true
    template: home/_entry.twig
    uriFormat: home
type: single
