defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9afae938-5b2e-48b4-8129-4f720b7bf9dd # hero
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0fad98d5-70b6-4371-8d2a-c5c8cd117e25: # Portfolio - Van Steenbergen Arno
    enabledByDefault: true
    hasUrls: true
    template: home/_entry.twig
    uriFormat: home
type: single
