defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 01f9a30f-b79d-4ac9-9c06-c4e9ceb41b18 # Project
handle: projectgrid
maxAuthors: 1
name: ProjectGrid
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0fad98d5-70b6-4371-8d2a-c5c8cd117e25: # Portfolio - Van Steenbergen Arno
    enabledByDefault: true
    hasUrls: true
    template: _projects/index
    uriFormat: 'projectgrid/{slug}'
type: channel
