defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 354864bf-8be4-4d4f-b2b3-6b3b0ab3a707 # projectdetail
handle: project
maxAuthors: 1
name: Project
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0fad98d5-70b6-4371-8d2a-c5c8cd117e25: # Portfolio - Van Steenbergen Arno
    enabledByDefault: true
    hasUrls: true
    template: _projects/_entry
    uriFormat: project
type: single
