currLabel: Assets
customIcon: null
enabled: true
handle: assets
icon: image
layout: 3f0de74b-a5af-4491-b091-b089a9e29f35 # Default
level: 1
newWindow: false
parent: null
prevLabel: Assets
prevLevel: 1
prevParent: null
prevUrl: assets
sortOrder: 9
type: craft
url: assets
