currLabel: Categories
customIcon: null
enabled: true
handle: categories
icon: sitemap
layout: 3f0de74b-a5af-4491-b091-b089a9e29f35 # Default
level: 1
newWindow: false
parent: null
prevLabel: Categories
prevLevel: 1
prevParent: null
prevUrl: categories
sortOrder: 10
type: craft
url: categories
