currLabel: GraphQL
customIcon: null
enabled: true
handle: graphql
icon: graphql
layout: 3f0de74b-a5af-4491-b091-b089a9e29f35 # Default
level: 1
newWindow: false
parent: null
prevLabel: GraphQL
prevLevel: 1
prevParent: null
prevUrl: graphql
sortOrder: 2
type: craft
url: graphql
