currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: gear
layout: 3f0de74b-a5af-4491-b091-b089a9e29f35 # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 7
type: craft
url: settings
