currLabel: Tokens
customIcon: null
enabled: true
handle: tokens
icon: null
layout: 3f0de74b-a5af-4491-b091-b089a9e29f35 # Default
level: 2
newWindow: false
parent: c1d19e66-776f-42d4-a8f8-7aabccec92ab
prevLabel: Tokens
prevLevel: 2
prevParent: c1d19e66-776f-42d4-a8f8-7aabccec92ab
prevUrl: graphql/tokens
sortOrder: 4
type: craft
url: graphql/tokens
