dateModified: 1741161842
email:
  fromEmail: arnowie1@gmail.com
  fromName: clean
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    101f5a9d-b6dc-48e3-bbc2-36e5159edc25: clean # clean
    cf36a3f0-408c-4770-96ef-41c24a40a0e2: clean # clean
system:
  edition: solo
  live: true
  name: clean
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
