color: purple
fieldLayouts:
  903bce54-7e5a-40fc-b4fe-0995f2f6279b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-12T08:37:36+00:00'
            elementCondition: null
            fieldUid: c59cd3a2-83c1-448b-a4be-e6eaf16556fb # image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9163475a-162e-4025-ac33-d37838b07a3b
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-10T12:07:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 05b4ad91-102e-4f9f-80d1-af2e209194c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T12:09:52+00:00'
            elementCondition: null
            fieldUid: a01e2fee-736a-42ef-ae9f-50f2d93b378c # Context
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63b2f7f4-ea6e-4017-aa65-5def5a9f8dbb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 30fe9d83-058f-45b5-bb2b-d529bdac78c9
        userCondition: null
handle: hero
hasTitleField: true
icon: compass
name: hero
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
