color: cyan
fieldLayouts:
  44a2c253-5271-46f1-be2d-8d01845158b2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-28T12:42:03+00:00'
            elementCondition: null
            fieldUid: c59cd3a2-83c1-448b-a4be-e6eaf16556fb # image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83b21b8c-2e68-4123-af52-d1ebc65cc64e
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-28T12:40:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fb4a5c74-c12f-4aeb-9e58-1ac195c5380d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-28T12:42:03+00:00'
            elementCondition: null
            fieldUid: a01e2fee-736a-42ef-ae9f-50f2d93b378c # Context
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0f438c2-5cc3-47de-a550-a493df713dca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-28T12:42:03+00:00'
            elementCondition: null
            fieldUid: 9cd4b5eb-0652-4e56-8542-fe7fb56d2d77 # UrlLink
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af744ad9-8085-48a7-8afe-61fa17d4bcc3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bcfe0200-1e39-43ea-a491-548a0be3d922
        userCondition: null
handle: projectdetail
hasTitleField: true
icon: asterisk
name: projectdetail
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
