color: cyan
fieldLayouts:
  abdd6fc6-244b-49f9-b0f7-3b2b42450a45:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-12T08:24:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4d8b86b7-4f63-4c84-bdc7-57f4fe004f95
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T08:26:18+00:00'
            elementCondition: null
            fieldUid: c59cd3a2-83c1-448b-a4be-e6eaf16556fb # image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6df7cfbe-a387-4b49-8445-3efb11243db2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T08:26:18+00:00'
            elementCondition: null
            fieldUid: a01e2fee-736a-42ef-ae9f-50f2d93b378c # Context
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce2b908c-6d13-4098-bbec-ab2035af707b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 736f4607-74f6-4e72-aa7c-58c287b1cb40
        userCondition: null
handle: project
hasTitleField: true
icon: rectangle-history
name: Project
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
