dateModified: 1740672976
email:
  fromEmail: arno.van.steenbergen1@gmail.com
  fromName: 'Craft Test'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    3f0de74b-a5af-4491-b091-b089a9e29f35: Default # Default
    9af51a79-286c-4914-a8bb-5e5361aee23c: 'Craft Test' # Craft Test
    eb3bd2cb-1645-4d40-a586-d3c9ed3018b6: 'Craft Test' # Craft Test
plugins:
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.11
system:
  edition: solo
  live: true
  name: 'Craft Test'
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: Europe/Amsterdam
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
